# Generated by Django 4.2 on 2023-05-24 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000, null=True)),
                ('followers_count', models.CharField(max_length=10000, null=True)),
                ('likes', models.CharField(max_length=100000, null=True)),
                ('signature', models.CharField(max_length=100000, null=True)),
                ('link', models.CharField(max_length=100000, null=True)),
                ('profile_photo_url', models.CharField(max_length=100000, null=True)),
                ('videos', models.TextField(null=True)),
            ],
        ),
    ]
