# Generated by Django 4.2 on 2023-05-26 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_profile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='category',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='follower',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='follower_info_state',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='region',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='uid',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
