# Generated by Django 4.2 on 2023-05-28 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followings',
            field=models.TextField(null=True),
        ),
    ]
