# Generated by Django 4.2 on 2023-06-03 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_profile_followings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='follower_info_state',
            new_name='all_feild_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='follower',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='followings',
        ),
        migrations.AddField(
            model_name='profile',
            name='state',
            field=models.CharField(choices=[('rapid api data initilized', 'rapid api data initilized'), ('scrapper data initilized', 'scrapper data initilized')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uid',
            field=models.CharField(max_length=10000, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='follower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=10000, null=True)),
                ('username', models.CharField(max_length=10000, null=True)),
                ('region', models.CharField(max_length=10000, null=True)),
                ('profile_photo', models.CharField(max_length=100000, null=True)),
                ('age', models.IntegerField(null=True)),
                ('signature', models.CharField(max_length=100000, null=True)),
                ('email', models.CharField(max_length=10000, null=True)),
                ('likes', models.CharField(max_length=100000, null=True)),
                ('follower_count', models.CharField(max_length=100000, null=True)),
                ('following_count', models.CharField(max_length=100000, null=True)),
                ('influencer', models.ForeignKey(max_length=10000, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.profile')),
            ],
        ),
    ]
