# Generated by Django 4.2 on 2023-06-03 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_follower_info_state_profile_all_feild_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='following_count',
            field=models.CharField(max_length=100000, null=True),
        ),
    ]
